package Project1;

import java.awt.Color;
import java.awt.Toolkit;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
*<pre>
* Class         About
* File          About.java
* Description   This is the About form that describe the application
* @author       <i>Nguyen Vi Cao</i>
* Environment   PC, Windows 10, jdk1.8.0_241, NetBeans 11.3
* Date          10/12/2020
* @version      1.0.0
* @see          javx.swing.frame
* History Log:  10/12/2020
*</pre>
*~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

public class About extends javax.swing.JDialog {

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *<pre>
 * Constructor      JDialog to allow to select modal or modeless form
 * Description      Create a GUI form and displayed it centered with icon and
 *                  calculateJButton set as default, and also set
 *                  background color
 * @author          <i>Nguyen Vi Cao</i>
 * Date             10/12/2020
 *</pre>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    public About(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // set CloseJButton as default
        this.getRootPane().setDefaultButton(CloseJButton);
        // set icon form
        this.setIconImage(Toolkit.getDefaultToolkit().
                getImage("src/Project1/Polygon-tool-icon.png"));
        // center the form at start
        this.setLocationRelativeTo(null);
        // change background color
        this.getContentPane().setBackground(Color.LIGHT_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleJLabel = new javax.swing.JLabel();
        RegularPolygonJScrollPane = new javax.swing.JScrollPane();
        RegularPolygonJTextArea = new javax.swing.JTextArea();
        CloseJButton = new javax.swing.JButton();
        CreatedByJLabel = new javax.swing.JLabel();
        WarningJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Regular Polygon About Form");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        TitleJLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TitleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/images.png"))); // NOI18N
        TitleJLabel.setText("About Regular Polygon");

        RegularPolygonJTextArea.setEditable(false);
        RegularPolygonJTextArea.setBackground(new java.awt.Color(204, 204, 255));
        RegularPolygonJTextArea.setColumns(20);
        RegularPolygonJTextArea.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        RegularPolygonJTextArea.setLineWrap(true);
        RegularPolygonJTextArea.setRows(5);
        RegularPolygonJTextArea.setText("Regular Polygons program calculates some measures of a regular polygon.\n\nRequired inputs are: number of sides n (integer), and length of the side s (double).\n\nThe calculations include: measure of interior angle, circumradius r, apothem a, perimeter p, area a, and error in approximating the circumference of the circumcircle with the perimeter of the polygon.");
        RegularPolygonJTextArea.setWrapStyleWord(true);
        RegularPolygonJScrollPane.setViewportView(RegularPolygonJTextArea);

        CloseJButton.setBackground(new java.awt.Color(153, 153, 0));
        CloseJButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CloseJButton.setMnemonic('c');
        CloseJButton.setText("Close");
        CloseJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseJButtonActionPerformed(evt);
            }
        });

        CreatedByJLabel.setText("Created by Vi Cao");

        WarningJLabel.setText("Copyrights: not free to use");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/Plabel.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(TitleJLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(CreatedByJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 202, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegularPolygonJScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(CloseJButton)
                        .addGap(131, 131, 131)
                        .addComponent(WarningJLabel)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegularPolygonJScrollPane)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CloseJButton, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(CreatedByJLabel)
                    .addComponent(WarningJLabel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    *<pre>
    * Method        quitJButtonActionPerformed()
    * Description   Closes the About form only
    * Date          10/12/2020
    * History Log   10/12/2020
    * @author       <i>Nguyen Vi Cao</i>	
    * @param        evt java.awt.event.ActionEvent
    *</pre>
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void CloseJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseJButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CloseJButtonActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseJButton;
    private javax.swing.JLabel CreatedByJLabel;
    private javax.swing.JScrollPane RegularPolygonJScrollPane;
    private javax.swing.JTextArea RegularPolygonJTextArea;
    private javax.swing.JLabel TitleJLabel;
    private javax.swing.JLabel WarningJLabel;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
